---
- name: Upgrade de todos os pacotes do S.O
  apt:
    update_cache: yes
    upgrade: dist
- name: instalação do git cliente
  apt:
    name: git
    state: latest
- name: configurar hosts lab ansible
  become: yes
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
    state: present
  loop:
    - "192.168.1.2 control-node"
    - "192.168.1.3 app01"
    - "192.168.1.4 db01"
