---
- name: configurar servidor de banco de dados
  hosts: db01
  become: yes
  user: vagrant


  vars_files:
    - vars/main.yml
  vars:
    dbname: "db01"
    dbusername: "root"
    dppassword: "011495"
  
  roles:
  - configuração-default-so
  - geerlingguy.mysql