---
mysql_root_password: "011495"
mysql_databases:
  - name: notes
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: notesapp
    host: "%"
    password: "011495"
    priv: "notes.*:ALL"